__version__ = '1.5.0'
__url__ = 'https://github.com/mdawar/rq-exporter'
__description__ = 'Prometheus exporter for Python RQ (Redis Queue)'
__author__ = 'Pierre Mdawar'
__author_email__ = 'pierre@mdawar.dev'
__license__ = 'MIT'
